### ISSUE TITLE
"ReferenceError: $a is not defined" when opening the contextMenu

### ISSUE THREAD

**Issue by ElephantRose** [Templarian/ui.bootstrap.contextMenu#10]
Hello,

Firstly thanks for your work. 
This is really easy to use.

I have found and error when opening the contextMenu.
with Angular 1.3.8 and jQuery 2.1.3.
tested in chrome 42 and IE 11

The error is thrown in the renderContextMenu on  :
```javascript
$a = $('<a>');
```

Changing it to : 
```javascript
var $a = $('<a>');
```
solved the issue for me. 

I think there is a variable conflict somewhere in one other directives that I'm using. 
To avoid it I suggest to restrict the $a variable to this scope only  (with the var keyword)

Have a good day

**Comment by Templarian** [comment]
https://github.com/Templarian/ui.bootstrap.contextMenu/commit/84f4ebac794f9ec4f2be3af14aa447bb0c154016

I'll need to publish a new version, but the repo is updated.

**Comment by ElephantRose** [comment]
great !

Thank you

**Comment by Templarian** [comment]
This was added in `v0.9.2`.
