### ISSUE TITLE
Close context menu in code

### ISSUE THREAD

**Issue by gwinnem** [Templarian/ui.bootstrap.contextMenu#106]
Is it possible to close the context menu in javascript ?

**Comment by josetaira** [comment]
Yup, you just need to trigger the jQuery event "mousedown" on $(document.body)

If you look at the code, you'll see there's a listener to this event. This will trigger all other mousedown events though. There's no direct way to close the contextmenu that's exposed currently. If you really need this, let me know.

**Comment by gwinnem** [comment]
I am triggering the below code:
But context menu is still open until i click the modal, but i need it to close automatically
$(document.body).trigger("mousedown");
                            var kendoTree = this.tree;
                            var dataItem = this.tree.dataItem(this.tree.select());
                            $scope.dataItem = kendoTree.dataItem(kendoTree.select());
                            var modalDefaults = { controller: "FolderAddController" };
                            var modalOptions = {
                                kendoTree: kendoTree,
                                dataItem: dataItem,
                                headerText: $scope.translation.AddFolder,
                                actionButtonText: $scope.translation.Save,
                                contentUrl: "Scripts/app/FileManager/Templates/folder-add-form.html"
                            };
                            $scope.openDialog(modalDefaults, modalOptions);

**Comment by josetaira** [comment]
What version of the context-menu are you using? If it's an old one this might work instead:

`$(".angular-bootstrap-contextmenu").mousedown()`

It's because the binding for the close was different before.

**Comment by gwinnem** [comment]
I am using the code from github but i still have the same issue.

**Comment by gwinnem** [comment]
Found a fix by adding $("ul").remove(".dropdown-menu"); to the code in the menu items to enforce that the menu is removed before i open my modal box.
