### ISSUE TITLE
[suggestion] add event hook before menu is shown

### ISSUE THREAD

**Issue by elgs** [Templarian/ui.bootstrap.contextMenu#11]
I'm hoping there will be an event hook callback just before the context menu is shown. If the event hook returns true (default), the context menu will be shown normally, otherwise, it will do nothing. What I need to do is to do some item selection things before the context menu is shown. So I think adding an event hook will be helpful.

**Comment by Templarian** [comment]
Like below?

```html
<ANY context-menu="menuOptions" context-menu-before="beforeContextMenu(scopeValue)"></ANY>
```

```javascript
$scope.beforeContextMenu = function (scopeValue) {
    if (scopeValue == '') {
        return false;
    }
};
```

**Comment by elgs** [comment]
Very close to what I was thinking. May be like this:

```html
<ANY context-menu="menuOptions" context-menu-before="beforeContextMenu"></ANY>
```
```javascript
$scope.beforeContextMenu = function ($itemScope) {
    // do whatever you like with the $itemScope, if you don't want the menu to show, return a false;
};
```

**Comment by Templarian** [comment]
Couldn't I just make menuOptions optionally allow a function instead and you simply return an empty array for no context-menu?

```html
<ANY context-menu="menuOptions" ></ANY>
```

```javascript
$scope.menuOptions = function () {
    // maybe return some custom menu options on click.
    return [];
};
```

**Comment by elgs** [comment]
Well, I have two goals:
1, to have a chance to do something before the menu is shown, that's important to me;
2, to decide to show the menu or not based on which item is right click on, that's just nice to have to me;

Changing `menuOptions` from array to function will perfectly satisfy my first goal, which is important to me. However, it doesn't help with the second goal. So I'm totally ok with changing menuOptions to a function.

**Comment by Templarian** [comment]
Uhh... you can definitely tell which one was clicked.

```html
<ANY ng-repeat="item in items">
    <ANY context-menu="menuOptions(item)" ></ANY>
</ANY>
```

```javascript
$scope.menuOptions = function (item) {
    if (item == 'foo') {
        // maybe return some custom menu options on click.
    }
    return [];
};
```

**Comment by elgs** [comment]
Aha, awesome!

Yes, that will be perfect! Thank you.

**Comment by Templarian** [comment]
This already works in the current version... I just never documented it.

http://jsfiddle.net/cLfpxp05/

**Comment by Templarian** [comment]
I'll take a minute and document soon. Ha.

**Comment by Templarian** [comment]
Oh wait, it doesn't handle 0 items. Fixing that now.

**Comment by Templarian** [comment]
Okay, fixed. Question, should it show the default context menu or still prevent the context menu?

Example:
http://jsfiddle.net/c6gba904/

**Comment by Templarian** [comment]
This was added in `v0.9.2`.

**Comment by elgs** [comment]
Thank you so much for add/documenting this feature. This feature will help me to handle item selection when user right clicks on the items.

I actually have no idea whether to show or prevent the default context menu.

**Comment by Templarian** [comment]
I've updated the example. Yea, I think just out right preventing always makes more sense since 99% of the time these will be used in list. Showing the default context menu would be very confusing.

**Comment by elgs** [comment]
Agreed. Thank you @Templarian. I appreciate your your awesome project and fast response to my questions.
