### ISSUE TITLE
Sub menu not getting closed

### ISSUE THREAD

**Issue by jbmyid** [Templarian/ui.bootstrap.contextMenu#111]
Sub menu not getting closed when moved focus out and focus in to item which doesn't have the subitems
<img width="358" alt="screen shot 2017-07-05 at 6 43 31 pm" src="https://user-images.githubusercontent.com/1590395/27865923-061f01b4-61b2-11e7-845d-68cb26a50a95.png">

**Comment by josetaira** [comment]
Hi @jbmyid, are you using the version from `master` or from the latest bower? I've checked the latest master and it seems to be working as expected. @Templarian, can we deploy a new bower build?

**Comment by jbmyid** [comment]
Using latest from bower.

**Comment by josetaira** [comment]
Yeah, it's just outdated. Once @Templarian deploys a new bower build from master it should be fine.

**Comment by jbmyid** [comment]
Cool Thanks

**Comment by nt9142** [comment]
It seems like npm repository also should be updated.
I just found another issue: Children menu items don't work with the new implementation.
But if I get the master version it will work.

**Comment by josetaira** [comment]
v1.0.0 is out and you should be able to get it from bower and npm now.
