### ISSUE TITLE
Accessing the element

### ISSUE THREAD

**Issue by jbmyid** [Templarian/ui.bootstrap.contextMenu#112]
How to access the element which we have added context menu on. No information in the event either.

**Comment by josetaira** [comment]
In the callback for the click, the second parameter is `event`. You can get the target from there. If you mean the exact option that was clicked, this is available as the 5th parameter.

**Comment by jbmyid** [comment]
No in the event target is not available, also 5th option is the li of context menu.

I want the element on which we do right click.

**Comment by josetaira** [comment]
@jbmyid what are the properties available in the event? Can you post them here?

**Comment by jbmyid** [comment]
It juts gives coordinates 
<img width="386" alt="screen shot 2017-07-10 at 10 57 03 am" src="https://user-images.githubusercontent.com/1590395/28003903-8dfcc788-655e-11e7-835e-fa3cd2cc8ca8.png">

**Comment by josetaira** [comment]
The event should now have a "target" which is the element the context menu was on.

**Comment by jbmyid** [comment]
cool thanks, when will it be available on bower?
