### ISSUE TITLE
Event when the context menu is closed without action

### ISSUE THREAD

**Issue by aitorMolinuevo** [Templarian/ui.bootstrap.contextMenu#114]
Hi,

I am using this awesome directive but I have a need that I cannot resolve. I have a timer thats stops when the context menu is opened and restarted when an action of the context menu is fired, the problem is when the user doesnt fire an action and just close the context menu I am not able to get an event when the context menu is closed. It is possible to achieve this?

Thanks in advance!

Nice work!

**Comment by josetaira** [comment]
See https://github.com/Templarian/ui.bootstrap.contextMenu#events
