### ISSUE TITLE
Adding promise support for main layout

### ISSUE THREAD

**Issue by yonatanarbel** [Templarian/ui.bootstrap.contextMenu#115]
So as for now, there is a support for "promise" return in case of children items

but sometimes I want to display item without children and display it according to info I get from the server.

therefore a support for promise return in the main layout is needed as well...
is there any plan to add this feature in the future?

is someone already working on it?

Thanks,
Yonatan

**Comment by josetaira** [comment]
Should be included in the latest master, and will be in the v1.0.1 release
