### ISSUE TITLE
Get Selected Item

### ISSUE THREAD

**Issue by RogerMito** [Templarian/ui.bootstrap.contextMenu#117]
Hello.
How do I get the selected element after the click event?
I have the $ itemScope variable, however I can not get the attributes of the element that was selected from the context menu.
Thank you.

**Comment by josetaira** [comment]
It's the 5th parameter passed to the onclick handler. See https://github.com/Templarian/ui.bootstrap.contextMenu#callback-parameters

**Comment by RogerMito** [comment]
Hello Friend.
I've already figured it out.
The contents of the context menu are obtained through AJAX calls.
However, I can not delay rendering, and whenever I select an item, the menu contents refer to the last selected variable. That is, in order for me to get the correct content for the current item, I must double-click that item.
How could you get around this problem?

Thank you.

**Comment by josetaira** [comment]
Hi @RogerMito, in version v1.1 (I'll release this soon), you can now use a Promise as your `menuOptions`. So you can just do something like:

```js
$scope.generateOptions = function() {
  // something that returns a promise
}
```

Then in your HTML something like:
```js
<div context-menu="generateOptions()" />
```

You can opt to point your build to the latest commit to test this out.
