### ISSUE TITLE
Text that comes from $filter('translate')('key') is not dynamically updated

### ISSUE THREAD

**Issue by Mouradif** [Templarian/ui.bootstrap.contextMenu#119]
Hi there,

Just a tiny issue here, everything is in the title, I have a `menuOption` array like this : 

```
	$scope.menuOptions = [
		{
			text: $filter('translate')("admin.invoice.DELETE"),
			click: function($itemScope, $event, modelValue, text, $li) {
				// code here
			}
		}
	]
```

But the text in the context menu stays the same as when the page was first loaded

**Comment by josetaira** [comment]
Hi @Mouradif could you provide a plunker sample of this?

**Comment by josetaira** [comment]
Nevermind, just try this out instead:

```js
$scope.menuOptions = [
		{
                        // use a function wrapper to return the text
			text: function() { return $filter('translate')("admin.invoice.DELETE"); },
			click: function($itemScope, $event, modelValue, text, $li) {
				// code here
			}
		}
	]
```
If the translation is made after the page is loaded, if you don't put it in a wrapper function the old text will not change.

**Comment by Mouradif** [comment]
It works ! Thanks
