### ISSUE TITLE
Open menu programmatically

### ISSUE THREAD

**Issue by augustoeliezer** [Templarian/ui.bootstrap.contextMenu#121]
Please, equal this: https://github.com/Templarian/ui.bootstrap.contextMenu/issues/120 Make a way to open on left click. In my case I have a link that will open a context menu, and I need to open this by left click too.

**Comment by josetaira** [comment]
It's just not documented properly, this is already supported using the `context-menu-on` property.

See the sample at: https://github.com/Templarian/ui.bootstrap.contextMenu#view
