### ISSUE TITLE
Property text doesn't accept a function

### ISSUE THREAD

**Issue by lafeuil** [Templarian/ui.bootstrap.contextMenu#122]
In the documentation, you specify that the property text of a menu can accept a string and a function : 
> text - [Function/String] A function that returns the string or the actual string itself

But, when I define a function, the item have a blank text.
In the code, the function is executed only with the legacy configuration.

**Comment by josetaira** [comment]
Thanks for reporting that @lafeuil. It should be fixed and will be in v1.1.0

**Comment by lafeuil** [comment]
@josetaira, It works ! 👍
Thanks for relaunching developments on this project 😃
