### ISSUE TITLE
Conditional divider 

### ISSUE THREAD

**Issue by lafeuil** [Templarian/ui.bootstrap.contextMenu#124]
With the current implementation, we can add divider in context menu by defining a null submenu.

But with the displayed property, we can hide some submenus but not the divider that precede them.

**Comment by josetaira** [comment]
Yeah, I'm actually in the process of implementing this. It's just another property in the object definition. Thinking of just a boolean/function property called "hasTopDivider". Just wondering if there are usecases for hasBottomDivider as well.

**Comment by josetaira** [comment]
Pushed and ready. The updated documentation now includes `hasTopDivider` and `hasBottomDivider`
