### ISSUE TITLE
3d level nested menu does not work, it closed leaving 2nd level

### ISSUE THREAD

**Issue by marcolazzarini** [Templarian/ui.bootstrap.contextMenu#127]
If I have a menu like option (i)-> nested 1 -> nested 2, when I leave second level, the third closes and it's not possible to select the desired option on 3rd level (actually, the one having the real action)

**Comment by josetaira** [comment]
Could you provide a demo or plunker for this? Thanks

**Comment by josetaira** [comment]
Nevermind, it's actually just a simple fix. Should be ready in the latest master and will be in 1.1.0

**Comment by marcolazzarini** [comment]
Thanks, when 1.1.0 will be ready?

**Comment by josetaira** [comment]
It should be ready now. I just released v1.1.0

**Comment by marcolazzarini** [comment]
thanks a lot, very good work! Just a note: documentation appears broken on github project page
