### ISSUE TITLE
New version on npm

### ISSUE THREAD

**Issue by v1r0x** [Templarian/ui.bootstrap.contextMenu#129]
Thanks for the new release. Like the new implementation! :)
I wanted to install the latest version using npm, but the latest npm version is still 0.9.9. Is this on purpose or is it supposed to be on 1.1.0?

**Comment by josetaira** [comment]
Thanks for reporting this. Turns out, I didn't have permission to perform the publish. But I've got it now and 1.1.0 is now available in NPM.

**Comment by v1r0x** [comment]
Thanks, that's great news :)
