### ISSUE TITLE
Ability to trigger row selection on opening context menu

### ISSUE THREAD

**Issue by vivaladan** [Templarian/ui.bootstrap.contextMenu#15]
It's possibly to manually select an element for the ng-repeat (in the scenario of a table) inside the handler for the context menu item. But this requires the context menu item to be clicked. To better illustrate to the user which row the context menu applies to it would be better to have the row selection happen when the menu opens.

This could potentially happen via configuration by providing a menu open hook so a developer can attach a handler that deals with selection the row.

**Comment by vivaladan** [comment]
Realised this has already been suggested https://github.com/Templarian/ui.bootstrap.contextMenu/issues/11

**Comment by Templarian** [comment]
No problem. Feel free to open issues in the future. It lets me know where the documentation needs to be updated also.

If I get a second I'll update the docs to explain this scenario since it is probably very common.
