### ISSUE TITLE
Multipe menu's opening in nested div's

### ISSUE THREAD

**Issue by malamili** [Templarian/ui.bootstrap.contextMenu#16]
When using nested divs that all show a menu, only the deepest div should 'catch' the contextmenu click. My workaround involves a 'event.stopPropagation();' line at the beginning of the directive. 

p.s. great work with the plugin! ;)

**Comment by Templarian** [comment]
This has already been fixed. I just never updated the bower, npm. I'll close this issue once I update.

https://github.com/Templarian/ui.bootstrap.contextMenu/pull/13

**Comment by Templarian** [comment]
Closed in bower `v0.9.4`.
