### ISSUE TITLE
Adding a context menu class name to dropdown

### ISSUE THREAD

**Issue by walexy** [Templarian/ui.bootstrap.contextMenu#22]
It could be useful to some to target the dropdown by  adding a contextmenu class to $contextMenu.addClass('dropdown clearfix');

Something like $contextMenu.addClass('contextmenu dropdown clearfix');

That way a designer can apply styles to the context menu without affecting other bootstrap dropdowns. Thanks for the the great plugin.

**Comment by josetaira** [comment]
https://github.com/Templarian/ui.bootstrap.contextMenu/commit/e2f1dbb761ed30e1b835e4a99d112f3b1d14b494 now adds the class `angular-bootstrap-contextmenu` to the dropdown. README has also been updated accordingly.
