### ISSUE TITLE
Unable to disable an option

### ISSUE THREAD

**Issue by Raghu-G** [Templarian/ui.bootstrap.contextMenu#23]
Hi,
When I try to set an option disabled, I'm unable to do it.
Below is my sample code:
            $scope.menuOptions = function (proc) {
                if (proc.id == 1) {
                    return ['John', 'Joe', [function ($itemScope, $event) {
                                                return $itemScope.proc.name;
                                            }, function ($itemScope, $event) {
                                            }, function ($itemScope, $event) {
                                                // Enable or Disable
                                                return false; // enabled = true, disabled = false
                                            }]
                    ];
                }
                return [
                    [function ($itemScope) {
                        return ['Name', 'Name2'];
                    }, function ($itemScope) {
                        return false;
                    }]
                ];
            };
If proc.id ==1, I'm trying to return 3 items, with third one being disabled. Am I doing something wrong here?

Appreciate your help in advance.

Thanks,
Raghu

**Comment by SuricateCan** [comment]
@Raghu-G You are doing everything wrong.

The menu options is supposed to be one array, where each menu item is a position inside this array.

That being said, each item is also an array, where the first position is the name of the item (of function with name), the second position is the action when clicked and the third position is a function for enable  disabled.

Your code should look something like this:

```
$scope.menuOptions = [
  ['John', function($itemScope, $event, $model){ /*do action*/ }, function($itemScope, $event, $model){ /*enable/disable*/ }],
  ['Joe', function($itemScope, $event, $model){ /*do action*/ }, function($itemScope, $event, $model){ /*enable/disable*/ }],
  ['Fulano', function($itemScope, $event, $model){ /*do action*/ }, function($itemScope, $event, $model){ /*enable/disable*/ }]  
];
```

**Comment by Templarian** [comment]
Correct. I'm going to close this issue out.
