### ISSUE TITLE
Publish component also to npm

### ISSUE THREAD

**Issue by lufecir** [Templarian/ui.bootstrap.contextMenu#26]
We are using NPM as dependency manager, also for the front-end libraries. It would be great if angular-bootstrap-contextmenu would also be published to NPM.
Now we have to create a package ourselves for each release and push it to our internal NPM server.

**Comment by aluanhaddad** [comment]
I would also appreciate this. This would benefit npm users and also jspm users.

**Comment by Templarian** [comment]
I see this issue, not ignoring it, just really busy lately. Will try to get to it next week.

**Comment by kentingxu** [comment]
We also use `npm` for front-end dependencies. And would appreciate if this is on npm.

**Comment by Templarian** [comment]
Done for `v0.9.5` with very basic nested context menu support.

`npm install angular-bootstrap-contextmenu`
