### ISSUE TITLE
directive rename

### ISSUE THREAD

**Issue by nobalmohan** [Templarian/ui.bootstrap.contextMenu#3]
If I rename the directive from "contextMenu" too something else, I get "undefined anonymous function" error during $apply ?

**Comment by Templarian** [comment]
https://github.com/Templarian/ui.bootstrap.contextMenu/blob/master/contextMenu.js#L68

Did you rename the attribute on line 68?

**Comment by nobalmohan** [comment]
oops. I missed that one. Works fine !

**Comment by Templarian** [comment]
Cool! :smile:
