### ISSUE TITLE
$ul[0].width and .offset are not functions

### ISSUE THREAD

**Issue by StevenRKM** [Templarian/ui.bootstrap.contextMenu#32]
Seems this is not available in JQlite.
And after some investigation, the version on the codepen demo does it correctly:

    var ev = {
        pageX: event.pageX + $ul[0].offsetWidth - 1,
        pageY: $ul[0].offsetTop + $li[0].offsetTop - 3
    };

While on the master it is this:

    $event.pageX = event.pageX + $ul.width();
    $event.pageY = $li.offset().top - 3;

**Comment by Templarian** [comment]
Sorry, should have branched, we're doing a lot of updates to support nesting. I have it almost done locally, but didn't push latest. Please use the version from NPM for now, or view the tags.

https://github.com/Templarian/ui.bootstrap.contextMenu/tree/v0.9.4

**Comment by Templarian** [comment]
My local works with JQlite, so don't worry about that. The pull request that I accepted was written for jQuery.

**Comment by StevenRKM** [comment]
No prob, just noticed it.
I was also checking it for the nested menus :)
It already works pretty nice!

**Comment by Templarian** [comment]
Yea, there are a few minor bugs I need to fix in the [demo](http://codepen.io/templarian/pen/VLKZLB), was using that to test out the changes.

**Comment by Templarian** [comment]
This if fixed in `v0.9.5`.
