### ISSUE TITLE
Drop Down menu does not open

### ISSUE THREAD

**Issue by jdoan3** [Templarian/ui.bootstrap.contextMenu#34]
I've been having this issue where I am trying to run the contextMenu via the example. I notice that the js works fine, but the dropdown box does not open. Is this because I have bootstrap and bootstrap ui which may be conflicting with the class?

**Comment by Templarian** [comment]
Maybe, can you edit the codepen demo in the readme to include the library you're including (setting button) and see if the issue persist. If this is a common issue we may need to tweak the context menu.

Link the codepen here once it can be reproduced.

**Comment by jdoan3** [comment]
So I believe I have found the issue, which was in my main.css in which there was a customization of the dropdown-menu. 

 .btn-group:not([data-animation]) .dropdown-menu, .dropdown:not([data-animation]) .dropdown-menu {
    -webkit-transform: scale(0);
    -ms-transform: scale(0);
    -o-transform: scale(0);
    transform: scale(0);
    opacity: 0;
    filter: alpha(opacity=0);
    display: block;
}

Is there a way to get around this or is this css really unimportant setting all the css of the dropdown to 0.

**Comment by Templarian** [comment]
Would the ability to rename the context menu class help? Like in #22.

**Comment by jdoan3** [comment]
I believe it had to deal with data-animations which caused this style to hit. Anyways I was able to resolve this.

Thanks though,
