### ISSUE TITLE
Feature: Allow for late loading of nested menu options

### ISSUE THREAD

**Issue by josetaira** [Templarian/ui.bootstrap.contextMenu#37]
Have a parameter you can specify that will be called to return the array that will be supplied to the nested menu before it is rendered. I'm thinking this can be simple function that returns the nested menu array which will be called before render menu of the nested arrays, or it can be an object, something like: {"nestedMenuLoader": function(){return []};}.

The object option might be better since from here any future new parameters can just be a new key in this object. Your thoughts?

**Comment by Templarian** [comment]
Probably easier to make `context-menu="menuOptions"` allow...

```javascript
$scope.menuOptions = function (name) {
    var deferred = $q.defer();
    setTimeout(function() {
        deferred.resolve([
            // resolved menu items.
        ]);
    }, 1000);
    return deferred.promise;
}
```

It already allows a function that returns an array so returning a promise would be easier to understand.

**Comment by josetaira** [comment]
@Templarian yeah, seems logical. Any plans on implementing this any time soon?

**Comment by josetaira** [comment]
I've implemented this and created a PR here: https://github.com/Templarian/ui.bootstrap.contextMenu/pull/52
