### ISSUE TITLE
Marker for nested menu looks ugly in firefox

### ISSUE THREAD

**Issue by madmas** [Templarian/ui.bootstrap.contextMenu#38]
With Firefox (tested with version 43 and 38), the marker for the nested menue is rendered in a new line, which looks ugly:

![bildschirmfoto 2016-01-21 um 17 11 03](https://cloud.githubusercontent.com/assets/37251/12486244/122f7ac6-c062-11e5-818e-f3098db505e7.png)

Solution is to add the (floating) marker first, I'll provide a PR in a minute.

**Comment by Templarian** [comment]
Thanks! Will review it shortly, but yea that definitely doesn't look nice in Firefox (kind of didn't want to use the Glyph font since a lot don't include it and opt for other font packages, especially when using themes).

**Comment by jamesrom** [comment]
Hey @Templarian I have checked this fix (49279e1) and it works. Can you please merge this (it's a one liner, check it out).

Firefox support is the only thing stopping me from using this otherwise awesome context menu.

**Comment by Templarian** [comment]
Merged, need to update the `bower` and `npm`.

**Comment by josetaira** [comment]
@Templarian the merge seems to have disappeared shortly after it was merged because of the refactoring that was done. I've added in a fix that closes this issue. We'll just have to update bower and npm accordingly.

**Comment by guicoma** [comment]
I'm not quite sure if I'm doing something wrong but the update doesn't seem to grab the correct code. Looking here at the tag of v0.9.7 it doesn't contain this fix. I guess I can grab it using the commit hash, but I believe the tag should be corrected.
