### ISSUE TITLE
Allow trigger customization - click or contextmenu

### ISSUE THREAD

**Issue by prasad83** [Templarian/ui.bootstrap.contextMenu#43]
Context-menu could be used like dynamic dropdown-menu as well - where click happens on handler.
Having trigger controlled from element attribute would make it easy.

```html
<a href="javascript:void(0);" context-menu="menuOptions" context-menu-trigger="click">M</a>
```

```javascript
return function ($scope, element, attrs) {
        var trigger = (attrs.contextMenuTrigger || 'contextmenu'); // <-- Customization
        element.on(trigger, function (event) {
```

**Comment by StevenRKM** [comment]
I agree, and this is a non-intrusive way of using another event for the contextmenu.
I did something similar for my project with only the left mouse button, but I like this better!

**Comment by janober** [comment]
Also +1 from me. Exactly what I would need right now

**Comment by josetaira** [comment]
Fixed by https://github.com/Templarian/ui.bootstrap.contextMenu/pull/66
