### ISSUE TITLE
Bower release is not syncronized with source on github

### ISSUE THREAD

**Issue by kris-kk** [Templarian/ui.bootstrap.contextMenu#44]
Installing using bower package manager... getting older version... any idea when a new release will be created?

**Comment by Templarian** [comment]
Sorry, the master branch is the working branch and isn't perfect ready for a release. Just use https://github.com/Templarian/ui.bootstrap.contextMenu/tree/v0.9.6 for now.

Sorry this project is lower on my priority list at the moment. Might try to find some time this weekend.

**Comment by josetaira** [comment]
v1.0.0 is ready for release and is synchronized now. Whenever we're ready for complete releases, I'll be making new ones available in npm and bower. @Templarian hope this is alright with you.
