### ISSUE TITLE
HTML Menu Labels

### ISSUE THREAD

**Issue by animsakari** [Templarian/ui.bootstrap.contextMenu#6]
Nice, light-weight module.  Very clean to use.  It might be nice to be able to embed HTML in the menu labels.  I plan to use this to embed fa icons in my menu for aesthetics.  Seems achievable by changing line 25 to use html() instead of text():
                $a.html(typeof item[0] == 'string' ? item[0] : item[0].call($scope, $scope));

**Comment by Templarian** [comment]
I don't know why issue #5 was closed. Reopening that and closing this issue. They had proposed the same thing. I'm going to add the ability once templates are added.

**Comment by Templarian** [comment]
I would rather follow the security model placed in Angular 1.3 rather than simply changing that line or adding a html: true etc...

**Comment by animsakari** [comment]
Excellent.  Sounds like the right way to go.  Thanks.
