### ISSUE TITLE
Dynamic Menu Item Text

### ISSUE THREAD

**Issue by BiggusCockus** [Templarian/ui.bootstrap.contextMenu#64]
Using the demo included in the release, I tried to change the text from "Buy" to "Buy <x>" where <x> is the item being selected. I understood that the "Buy" string can be replaced with a function so I used the following configuration:

```
   $scope.menuOptions = [
        [function ($itemScope) {
            return "Buy " + $itemScope.item.name;
        }, function ($itemScope) {
            $scope.player.gold -= $itemScope.item.cost;
        }],
        null,
        ['Sell', function ($itemScope) {
            $scope.player.gold += $itemScope.item.cost;
        }, function ($itemScope) {
            return $itemScope.item.name.match(/Iron/) == null;
        }],
        null,
        ['More...', [
            ['Alert Cost', function ($itemScope) {
                alert($itemScope.item.cost);
            }],
            ['Alert Player Gold', function ($itemScope) {
                alert($scope.player.gold);
            }]
        ]]
    ];
```

The first menu item is displayed as "New Item"

![screen shot 2016-05-27 at 10 02 18 am](https://cloud.githubusercontent.com/assets/16840018/15603355/2d49fba8-23f2-11e6-8999-78701cc55e66.png)

**Comment by intrepido** [comment]
Same problem the dynamic item doesn't work

**Comment by josetaira** [comment]
@BiggusCockus @intrepido if you could just confirm if this is already fixed in the latest commit that'd be great.
