### ISSUE TITLE
Using the context-menu from inside a bootstrap submenu closes the parent menu

### ISSUE THREAD

**Issue by wagedomain** [Templarian/ui.bootstrap.contextMenu#67]
As the title says, if you use the context-menu inside of a bootstrap submenu, opening the context menu closes the parent, leaving the context menu floating in the screen visibly attached to nothing.

**Comment by josetaira** [comment]
A plunkr with a demo would be really helpful here.

**Comment by wagedomain** [comment]
After investigating, it's because using the context menu causes a brief "unhover" of the bootstrap submenu and that causes it to hide. A workaround I built is to simply capture the right-click event on the element and "pinning" the bootstrap menu open until something triggers it to close. 

Not sure if or what the events are for this and if there's an "onClose" event or not... still investigating.

**Comment by josetaira** [comment]
If this is still relevant, feel free to create a new issue and reference this instead. Closing since you have a workaround.
