### ISSUE TITLE
Bower package seems to be a different, older version

### ISSUE THREAD

**Issue by joshchua** [Templarian/ui.bootstrap.contextMenu#71]
The contextMenu.js from Bower doesnt have contextMenuOn that is here on the GitHub repo

**Comment by saulo2** [comment]
I am facing the same problem. When do you plan to releage a new version?

**Comment by Templarian** [comment]
Oh yea, always forget about this project... yes. I'll do a code check this week and try and get bower/npm updated with a new version.

**Comment by AOlkar** [comment]
This still is the same older version off Bower.

**Comment by beauraines** [comment]
This is not a long term solution...

You can grab master by  putting this line in your `bower.json` instead of the version that is specified

```
    "angular-bootstrap-contextmenu": "https://github.com/Templarian/ui.bootstrap.contextMenu.git#master"
``

**Comment by saulo2** [comment]
A slightly better option is to indicate an specifi commit:

"https://github.com/Templarian/ui.bootstrap.contextMenu.git#12b9eef"

**Comment by guicoma** [comment]
Yes, ran into this issue when I saw that on Firefox nested menu didn't look quite right. Will use the specific commit for now. Thanks!

**Comment by Templarian** [comment]
Updated to `v0.9.8`, sorry been really busy. Will try to not ignore this project from now on.

**Comment by saulo2** [comment]
Hi Templarian, I am glad you managed to find some time to work in the project again. It is a wonderful component. Thanks a lot. Keep the good work!

**Comment by josetaira** [comment]
@Templarian, if you could inform me on the procedures on how to put the latest version into bower, I'd be able to update it when you're too busy.

**Comment by Templarian** [comment]
@josetaira Bower is simply updating the bower.json version and git tagging. Same with NPM's package file, but to do a `NPM publish` I need to add you as a user.
