### ISSUE TITLE
Know which option has been selected

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [Templarian/ui.bootstrap.contextMenu#72]
I'm currently trying to use this directive to load a dynamic Menu with dynamic functions. I wanted to know what option has been selected of the menu to then invoke a function in my controller but apparently I can't. Is there a way in the current release?

**Comment by shihalv** [comment]
I need the same thing.  Pre-select the item, then open the context menu.

**Comment by josetaira** [comment]
I've added the list item that's selected as a parameter in the callback. Is this what you were looking for @tiagomsmagalhaes, @shihalv?

**Comment by AlexJH4U** [comment]
@josetaira Yes, that's exactly what is needed -- but I'm not seeing any parameter representing the selected item.

**Comment by josetaira** [comment]
Closing this from lack of response. If what I added wasn't what you were looking for, kindly reopen this ticket and describe what you need.
