### ISSUE TITLE
Check if all values returns true or false

### ISSUE THREAD

**Issue by davidedellai** [Templarian/ui.bootstrap.contextMenu#73]
I will report what I wrote on stackoverflow:

Look at this function:

`var registerEnabledEvents = function ($scope, enabled, item, $ul, $li, nestedMenu, model, text, event, $, level) {
            /// <summary>

If item is enabled, register various mouse events.</summary>

            if (enabled) {
                var openNestedMenu = function ($event) {
                    removeContextMenus(level + 1);
                    var ev = {
                        pageX: event.pageX + $ul[0].offsetWidth - 1,
                        pageY: $ul[0].offsetTop + $li[0].offsetTop - 3
                    };
                    renderContextMenu($scope, ev, nestedMenu, model, level + 1);
                };

```
            $li.on('click', function ($event) {
                $event.preventDefault();
                $scope.$apply(function () {
                    if (nestedMenu) {
                        openNestedMenu($event);
                    } else {
                        $(event.currentTarget).removeClass('context');
                        removeContextMenus();

                        if (angular.isFunction(item[1])) {
                            item[1].call($scope, $scope, event, model, text)
                        } else {
                            item.click.call($scope, $scope, event, model, text);
                        }
                    }
                });
            });

            $li.on('mouseover', function ($event) {
                $scope.$apply(function () {
                    if (nestedMenu) {
                        openNestedMenu($event);
                    }
                });
            });
        } else {
            $li.on('click', function ($event) {
                $event.preventDefault();
            });
            $li.addClass('display-none');
        }

    };`
```

 Actually there isn't any way to hide a list item of the menu by a parameter or condition so i modified the directive. i changed:

   `$li.addClass('disabled');`

with

```
`$li.addClass('display-none');`
```

It works. If an item returns `false` it doesn't display it. What's the problem? Well the "enabled" parameter returns if the items of the context menu are visible or not. If you write down a console.log() and display that value it will get (if you have 2 items for example):

```
`2016-07-08 12:54:36.851 contextMenu.js:141 false 
2016-07-08 12:54:36.854 contextMenu.js:141 false`
```

or

```
`2016-07-08 12:54:36.851 contextMenu.js:141 true 
2016-07-08 12:54:36.854 contextMenu.js:141 false`
```

it depends of course from the conditions in the controller. The problem is that if all items returns false, the context menu it shows without items, but it shows with just a "white empty rectangle". What i need it should be that if all items returns false i add the class display-none to the entire ul like this:

```
`$ul.addClass('display-none');`
```

but if at least one is true i add the css class only to the $li item to hide only the one return false. How can i do it? Thank you

**Comment by josetaira** [comment]
You can use the newly added 'displayed' parameter. This will be available in v1.0.1
