### ISSUE TITLE
popup blinks on menu item which has nested menu on mouse over

### ISSUE THREAD

**Issue by sachinkhot02** [Templarian/ui.bootstrap.contextMenu#75]
when I mouse hover on the item which has nested  poup then the all that is the parent and sub popup blinks and render.

**Comment by josetaira** [comment]
Hi @sachinkhot02, could you try this on the latest build? If it doesn't occur anymore, kindly close the ticket. If you can still replicate it, please provide a plunker with a demo. Thanks

**Comment by josetaira** [comment]
Closing as this can't be replicated anymore. If it's still an issue, kindly provide a plunkr to demonstrate, or a gif.
