### ISSUE TITLE
Add hide menu option

### ISSUE THREAD

**Issue by alexander2209** [Templarian/ui.bootstrap.contextMenu#76]
I know we can disable menu options, but they still show up and look exactly the same but I am unable to click. I would LOVE it if you could actually prevent these menu items from showing at all. Like an ng-hide or something.

**Comment by Templarian** [comment]
This was considered and may still be added for now look at the last code block in menu options. You can use a function for menu options and push to an array each menu item and return it.

https://github.com/Templarian/ui.bootstrap.contextMenu#menu-options

**Comment by josetaira** [comment]
I've also added the feature before so that function can also return a promise, which can resolve to an array containing exactly what you want it to display.
