### ISSUE TITLE
Firefox's default context menu still pops up

### ISSUE THREAD

**Issue by Asheq** [Templarian/ui.bootstrap.contextMenu#77]
In Firefox (version 45.2.0), Firefox's default context menu still pops up, potentially covering up the one generated by angular directive as shown in the picture below:

![image](https://cloud.githubusercontent.com/assets/4657140/16819884/5073efa4-4903-11e6-881a-609bfb25f49d.png)

**Comment by Templarian** [comment]
On 47 it right clicks fine, that example codepen needs to be updated as it contains the broken arrow in Firefox.

You may have an addon or something installed also. Try safe mode.

**Comment by Asheq** [comment]
Thanks for looking at this.

I solved the issue by entering **about:config** into the Firefox address bar and changed **dom.event.contextmenu.enabled** to true.

(This link steered me in the right direction: https://support.mozilla.org/en-US/questions/960253)

**Comment by Templarian** [comment]
Yea, might be a company wide setting. Some org's IT modify random defaults like this because they think they hare helping the user.

Good to see you found a solution. :smile:
