### ISSUE TITLE
menu option [Function, Function] format not working on 0.9.7

### ISSUE THREAD

**Issue by chessychev** [Templarian/ui.bootstrap.contextMenu#79]
works on 0.9.6, broken on 0.9.7.
the first of the two function is probably not called, since the menu option is always "New Item" (probably the default for a menu option when no other string is provided).

**Comment by vnishukov** [comment]
Have the same issue on 0.9.7

**Comment by josetaira** [comment]
Hi @chessychev @vnishukov, can you provide a plunkr for this? I'll check it out once you do. Thanks

**Comment by carsey** [comment]
Having the same issue.

**Comment by carsey** [comment]
Codepen: http://codepen.io/anon/pen/QEJZmr
It is fixed with most recent commits, but on 0.9.7 tag it is broken.

**Comment by Templarian** [comment]
This was fixed in `v0.9.8`. Closing the issue.
