### ISSUE TITLE
Left click binding is not working

### ISSUE THREAD

**Issue by omidn** [Templarian/ui.bootstrap.contextMenu#81]
Dear,

I installed the module according to the instructions on Readme.md and got it running. This options seem not to be working for me.
```

<div>
    <span>you can specify the event on how the menu opens:</span>
    <div ng-repeat="item in items" context-menu="menuOptions" context-menu-on="click">Left Click: {{item.name}}</div>
</div>
<div ng-bind="selected"></div>

```

Albeit I have defined that **context-menu-on="click"**.
Any ideas?

**Comment by einarj** [comment]
I have that issue as well. Added context-menu-on="click" to the codepen example but it still only triggers on right-click.

**Comment by Templarian** [comment]
http://codepen.io/templarian/pen/kXOjVp Just tried it (the demo codepen has been updated with `v0.9.8`.

Appears to work, might have been a bug.

**Comment by einarj** [comment]
Verified, awesome. Thanks for the update.

**Comment by omidn** [comment]
Awesome, Thanks
