### ISSUE TITLE
0.9.7 version of the use of three parameters, the menu name will be displayed as [new item]. Instead of the [name] .

### ISSUE THREAD

**Issue by 721687** [Templarian/ui.bootstrap.contextMenu#83]
0.9.7 version of the use of three parameters, the menu name will be displayed as [new item]. Instead of the [name] .

`$scope.menuOptions = [
         [function(){
            return 'name';
          }, function ($itemScope) {
          }, function ($itemScope) {
          }]
      ];`

**Comment by Templarian** [comment]
Can you retest this for `v0.9.8`, it might be fixed.

**Comment by 721687** [comment]
0.9.8 is ok, thanks!
