### ISSUE TITLE
Context menu is not closed on click outside menu

### ISSUE THREAD

**Issue by prikryl** [Templarian/ui.bootstrap.contextMenu#84]
fix:
contextmenu.js
```
       function removeAllContextMenus(e) {
            if ($(e.target).hasClass("dropdown")) { // menu is not closed of clicked outside contextmenu- bug in original sources
                removeContextMenus();
                return;
            }
             if (!$(e.target).closest('.dropdown').length) {
                removeContextMenus();
            }
        }
````

**Comment by josetaira** [comment]
Weird. This used to work on a previous version. Probably one of the recent "fixes" and changes broke this. I'm working on it.

**Comment by josetaira** [comment]
"closest" is not available in jQLite. The change in https://github.com/Templarian/ui.bootstrap.contextMenu/pull/63 broke this. We should make sure that changes coming into this repo do not have any jQuery-only code.

Should be available in the next build in bower and npm. @Templarian for your action

**Comment by Templarian** [comment]
@josetaira v0.9.9 released. Eventually I guess I'll have to make this a v1.0.0 release.
