### ISSUE TITLE
Context menu not being removed

### ISSUE THREAD

**Issue by gconey** [Templarian/ui.bootstrap.contextMenu#98]
The last commit seems to have introduced a bug where the context menu isn't removed when the user clicks outside it. I fixed this by changing the following line in removeAllContextMenus:
Changed `if ( !$(event.currentTarget).hasClass('context') ) {`
to `if ( $(event.currentTarget).hasClass('context') ) {`

**Comment by devginie** [comment]
I am in same problem. Therefore, I resolve that following code : 

`if ( !$(event.currentTarget).hasClass('dropdown-menu') ) {`

Any problem this code?

**Comment by josetaira** [comment]
Hi @gconey @devginie are you referring to the latest bower version or the latest commit at d8ca2d4? I just tried d8ca2d4 and it seems to be working as expected.

**Comment by gconey** [comment]
The problem is in the latest commit.

**Comment by josetaira** [comment]
![click-out-issue](https://cloud.githubusercontent.com/assets/15209679/21977969/6b7c9bce-dbd0-11e6-84ec-6df564226e26.gif)

This is what I'm encountering. Seems like I can only replicate it when clicking outside the bounds of the html (the part that gets highlighted in blue). Is this the same thing for you? Particularly, when you click within the bounds of the <html></html> does it work?

**Comment by gconey** [comment]
The problem I saw was that clicking anywhere outside the context menu didn’t hide the context menu.
I am using the latest ver of Chrome.
The small change I suggested has fixed the issue completely.

Regards,
George
